# Generated by Django 3.2.10 on 2024-10-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=15)),
                ('afiliado', models.CharField(max_length=25)),
                ('tarea', models.CharField(max_length=25)),
            ],
        ),
    ]
